# Generated by Django 3.2.7 on 2022-05-26 09:34

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250, verbose_name='Property Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(max_length=100, verbose_name='Property Reference Code')),
                ('description', models.TextField(default='Default Description', verbose_name='Description')),
                ('country', django_countries.fields.CountryField(default='BD', help_text='Select Country', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Dhaka', max_length=120, verbose_name='City')),
                ('postal_code', models.CharField(default='', max_length=255, verbose_name='Postal Code')),
                ('street_address', models.CharField(default='', max_length=255, verbose_name='Stree Address')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(m^2)')),
                ('property_number', models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0.15, help_text='Tax percent', max_digits=6, verbose_name='Tax')),
                ('total_floors', models.IntegerField(default=0, verbose_name='Total Floors')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='Bathrooms')),
                ('advert_type', models.CharField(choices=[('For sale', 'For sale'), ('For rent', 'For rent'), ('For auction', 'For auction')], default='For sale', max_length=255, verbose_name='Advertise Type')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Other', 'Other')], default='Other', max_length=255, verbose_name='Prpperty type')),
                ('cover_photo', models.ImageField(blank=True, default='/property/default.png', null=True, upload_to='', verbose_name='Cover Image')),
                ('photo1', models.ImageField(blank=True, default='/property/default1.png', null=True, upload_to='', verbose_name='Interior Photo 1')),
                ('photo2', models.ImageField(blank=True, default='/property/default2.png', null=True, upload_to='', verbose_name='Interior Photo 2')),
                ('photo3', models.ImageField(blank=True, default='/property/default3.png', null=True, upload_to='', verbose_name='Interior Photo 3')),
                ('photo4', models.ImageField(blank=True, default='/property/default4.png', null=True, upload_to='', verbose_name='Interior Photo 4')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published Status')),
                ('views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agnet, seller or buyer')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255, verbose_name='IP Address')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property View',
                'verbose_name_plural': 'Property views',
            },
        ),
    ]
