# Generated by Django 3.2.7 on 2022-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Property Reference Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='property tax charged', max_digits=6, verbose_name='Property Tax'),
        ),
    ]
