# Generated by Django 3.2.7 on 2022-05-24 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 8, 23, 9, 115507, tzinfo=utc)),
        ),
    ]
